// <auto-generated />
using Formul.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Formul.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221110172714_formula")]
    partial class formula
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Formul.Entities.Formula", b =>
                {
                    b.Property<int>("FormulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FormulaId"));

                    b.Property<string>("FormulaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FormulaId");

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("Formul.Entities.Parametr", b =>
                {
                    b.Property<int>("ParametrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParametrId"));

                    b.Property<int>("ParametrValue")
                        .HasColumnType("integer");

                    b.HasKey("ParametrId");

                    b.ToTable("Parametrs");
                });
#pragma warning restore 612, 618
        }
    }
}
